#
# This model specification was automatically generated by Onyx
#
library(lavaan)
library(dplyr)

###set your working directory to where the data lives
setwd(basedir)

###ONYX generated, but we need to be more explicit about reading data
# modelData <- read.table(DATAFILENAME, header = TRUE) ;
modelData <- read.csv("simple_regression_data.csv", header = TRUE, sep = "\t") %>% rename(Parent_IQ = X_c, Child_IQ = Y_c)
 model<-"
! regressions 
   Child_IQ ~ Parent_IQ__Child_IQ*Parent_IQ
! residuals, variances and covariances
   Parent_IQ ~~ VAR_Parent_IQ*Parent_IQ
   Child_IQ ~~ VAR_Child_IQ*Child_IQ
! observed means
   Parent_IQ~1;
   Child_IQ~1;
";
result<-lavaan(model, data=modelData, fixed.x=FALSE, missing="FIML")
summary(result, fit.measures=TRUE)
